const productData = [
  {
    ticker: 'BMAE',
    url: '#',
    criteria: 'Municipal Fixed Income',
    maturityDate: 2021,
    yieldToMaturity: 3.75,
    yieldToWorst: 3.74,
    effectiveDuration: 1.87,
    monthSecYield: 3.42,
    distributionRate: 'N/A',
    numberOfHoldings: 49,
    creditQuality: {
      aaa: '14%',
      aa: '2%',
      a: '11%',
      bbb: '43%',
      bb: '21%',
      b: '0%',
      ccc: '0%',
      cc: '0%',
      c: '0%',
      d: '0%',
      nr: '9%'
    }
  },
  {
    ticker: 'BMBE',
    url: '#',
    criteria: 'Municipal Fixed Income',
    maturityDate: 2022,
    yieldToMaturity: 3.92,
    yieldToWorst: 3.92,
    effectiveDuration: 2.76,
    monthSecYield: 3.76,
    distributionRate: 'N/A',
    numberOfHoldings: 54,
    creditQuality: {
      aaa: '14%',
      aa: '2%',
      a: '11%',
      bbb: '43%',
      bb: '21%',
      b: '0%',
      ccc: '0%',
      cc: '0%',
      c: '0%',
      d: '0%',
      nr: '9%'
    }
  },
  {
    ticker: 'BMCE',
    url: '#',
    criteria: 'Municipal Fixed Income',
    maturityDate: 2023,
    yieldToMaturity: 3.96,
    yieldToWorst: 3.96,
    effectiveDuration: 3.51,
    monthSecYield: 3.88,
    distributionRate: 'N/A',
    numberOfHoldings: 48,
    creditQuality: {
      aaa: '14%',
      aa: '2%',
      a: '11%',
      bbb: '43%',
      bb: '21%',
      b: '0%',
      ccc: '0%',
      cc: '0%',
      c: '0%',
      d: '0%',
      nr: '9%'
    }
  },
  {
    ticker: 'BSCJ',
    url: '#',
    criteria: 'Investment Grade',
    maturityDate: 2019,
    yieldToMaturity: 2.26,
    yieldToWorst: 2.24,
    effectiveDuration: 0.22,
    monthSecYield: 2.41,
    distributionRate: 2.32,
    numberOfHoldings: 140,
    creditQuality: {
      aaa: '2%',
      aa: '21%',
      a: '33%',
      bbb: '42%',
      bb: '1%',
      b: '0%',
      ccc: '0%',
      cc: '0%',
      c: '0%',
      d: '0%',
      nr: '1%'
    }
  },
  {
    ticker: 'BSCK',
    url: '#',
    criteria: 'Investment Grade',
    maturityDate: 2020,
    yieldToMaturity: 2.41,
    yieldToWorst: 2.36,
    effectiveDuration: 0.95,
    monthSecYield: 2.43,
    distributionRate: 2.5,
    numberOfHoldings: 371,
    creditQuality: {
      aaa: '2%',
      aa: '14%',
      a: '42%',
      bbb: '41%',
      bb: '1%',
      b: '0%',
      ccc: '0%',
      cc: '0%',
      c: '0%',
      d: '0%',
      nr: '1%'
    }
  },
  {
    ticker: 'BSCL',
    url: '#',
    criteria: 'Investment Grade',
    maturityDate: 2021,
    yieldToMaturity: 2.45,
    yieldToWorst: 2.41,
    effectiveDuration: 1.81,
    monthSecYield: 2.46,
    distributionRate: 2.71,
    numberOfHoldings: 402,
    creditQuality: {
      aaa: '1%',
      aa: '14%',
      a: '43%',
      bbb: '42%',
      bb: '1%',
      b: '0%',
      ccc: '0%',
      cc: '0%',
      c: '0%',
      d: '0%',
      nr: '0%'
    }
  },
  {
    ticker: 'BSCM',
    url: '#',
    criteria: 'Investment Grade',
    maturityDate: 2022,
    yieldToMaturity: 2.53,
    yieldToWorst: 2.5,
    effectiveDuration: 2.75,
    monthSecYield: 2.56,
    distributionRate: 2.85,
    numberOfHoldings: 386,
    creditQuality: {
      aaa: '2%',
      aa: '10%',
      a: '38%',
      bbb: '47%',
      bb: '3%',
      b: '0%',
      ccc: '0%',
      cc: '0%',
      c: '0%',
      d: '0%',
      nr: '0%'
    }
  },
  {
    ticker: 'BSCN',
    url: '#',
    criteria: 'Investment Grade',
    maturityDate: 2023,
    yieldToMaturity: 2.62,
    yieldToWorst: 2.59,
    effectiveDuration: 3.5,
    monthSecYield: 2.64,
    distributionRate: 3.01,
    numberOfHoldings: 321,
    creditQuality: {
      aaa: '2%',
      aa: '13%',
      a: '34%',
      bbb: '49%',
      bb: '2%',
      b: '0%',
      ccc: '0%',
      cc: '0%',
      c: '0%',
      d: '0%',
      nr: '0%'
    }
  },
  {
    ticker: 'BSCO',
    url: '#',
    criteria: 'Investment Grade',
    maturityDate: 2024,
    yieldToMaturity: 2.78,
    yieldToWorst: 2.75,
    effectiveDuration: 4.35,
    monthSecYield: 2.82,
    distributionRate: 3.14,
    numberOfHoldings: 242,
    creditQuality: {
      aaa: '1%',
      aa: '11%',
      a: '33%',
      bbb: '52%',
      bb: '3%',
      b: '0%',
      ccc: '0%',
      cc: '0%',
      c: '0%',
      d: '0%',
      nr: '1%'
    }
  },
  {
    ticker: 'BSCP',
    url: '#',
    criteria: 'Investment Grade',
    maturityDate: 2025,
    yieldToMaturity: 2.94,
    yieldToWorst: 2.91,
    effectiveDuration: 5.16,
    monthSecYield: 2.95,
    distributionRate: 3.28,
    numberOfHoldings: 242,
    creditQuality: {
      aaa: '2%',
      aa: '10%',
      a: '29%',
      bbb: '57%',
      bb: '1%',
      b: '0%',
      ccc: '0%',
      cc: '0%',
      c: '0%',
      d: '0%',
      nr: '1%'
    }
  },
  {
    ticker: 'BSCQ',
    url: '#',
    criteria: 'Investment Grade',
    maturityDate: 2026,
    yieldToMaturity: 3.09,
    yieldToWorst: 3.08,
    effectiveDuration: 6.01,
    monthSecYield: 3.12,
    distributionRate: 3.32,
    numberOfHoldings: 250,
    creditQuality: {
      aaa: '2%',
      aa: '10%',
      a: '33%',
      bbb: '53%',
      bb: '2%',
      b: '0%',
      ccc: '0%',
      cc: '0%',
      c: '0%',
      d: '0%',
      nr: '0%'
    }
  },
  {
    ticker: 'BSCR',
    url: '#',
    criteria: 'Investment Grade',
    maturityDate: 2027,
    yieldToMaturity: 3.18,
    yieldToWorst: 3.16,
    effectiveDuration: 6.67,
    monthSecYield: 3.2,
    distributionRate: 3.53,
    numberOfHoldings: 216,
    creditQuality: {
      aaa: '2%',
      aa: '10%',
      a: '30%',
      bbb: '57%',
      bb: '1%',
      b: '0%',
      ccc: '0%',
      cc: '0%',
      c: '0%',
      d: '0%',
      nr: '0%'
    }
  },
  {
    ticker: 'BSCS',
    url: '#',
    criteria: 'Investment Grade',
    maturityDate: 2028,
    yieldToMaturity: 3.26,
    yieldToWorst: 3.25,
    effectiveDuration: 7.21,
    monthSecYield: 3.28,
    distributionRate: 3.67,
    numberOfHoldings: 147,
    creditQuality: {
      aaa: '1%',
      aa: '6%',
      a: '32%',
      bbb: '59%',
      bb: '2%',
      b: '0%',
      ccc: '0%',
      cc: '0%',
      c: '0%',
      d: '0%',
      nr: '0%'
    }
  },
  {
    ticker: 'BSJK',
    url: '#',
    criteria: 'High Yield',
    maturityDate: 2020,
    yieldToMaturity: 4.56,
    yieldToWorst: 3.37,
    effectiveDuration: 0.77,
    monthSecYield: 3.93,
    distributionRate: 4.16,
    numberOfHoldings: 71,
    creditQuality: {
      aaa: '0%',
      aa: '0%',
      a: '0%',
      bbb: '2%',
      bb: '47%',
      b: '44%',
      ccc: '4%',
      cc: '0%',
      c: '0%',
      d: '0%',
      nr: '2%'
    }
  },
  {
    ticker: 'BSJL',
    url: '#',
    criteria: 'High Yield',
    maturityDate: 2021,
    yieldToMaturity: 5.16,
    yieldToWorst: 4.33,
    effectiveDuration: 1.4,
    monthSecYield: 5.04,
    distributionRate: 5.17,
    numberOfHoldings: 112,
    creditQuality: {
      aaa: '0%',
      aa: '0%',
      a: '0%',
      bbb: '0%',
      bb: '50%',
      b: '42%',
      ccc: '7%',
      cc: '0%',
      c: '0%',
      d: '0%',
      nr: '1%'
    }
  },
  {
    ticker: 'BSJM',
    url: '#',
    criteria: 'High Yield',
    maturityDate: 2022,
    yieldToMaturity: 5.35,
    yieldToWorst: 4.19,
    effectiveDuration: 1.53,
    monthSecYield: 4.97,
    distributionRate: 5.35,
    numberOfHoldings: 173,
    creditQuality: {
      aaa: '0%',
      aa: '0%',
      a: '0%',
      bbb: '0%',
      bb: '51%',
      b: '38%',
      ccc: '10%',
      cc: '0%',
      c: '0%',
      d: '0%',
      nr: '1%'
    }
  },
  {
    ticker: 'BSJN',
    url: '#',
    criteria: 'High Yield',
    maturityDate: 2023,
    yieldToMaturity: 5.76,
    yieldToWorst: 4.65,
    effectiveDuration: 1.97,
    monthSecYield: 5.44,
    distributionRate: 5.57,
    numberOfHoldings: 213,
    creditQuality: {
      aaa: '0%',
      aa: '0%',
      a: '0%',
      bbb: '1%',
      bb: '44%',
      b: '44%',
      ccc: '9%',
      cc: '0%',
      c: '0%',
      d: '0%',
      nr: '1%'
    }
  },
  {
    ticker: 'BSJO',
    url: '#',
    criteria: 'High Yield',
    maturityDate: 2024,
    yieldToMaturity: 5.19,
    yieldToWorst: 4.1,
    effectiveDuration: 2.0,
    monthSecYield: 5.03,
    distributionRate: 5.12,
    numberOfHoldings: 199,
    creditQuality: {
      aaa: '0%',
      aa: '0%',
      a: '0%',
      bbb: '1%',
      bb: '55%',
      b: '35%',
      ccc: '7%',
      cc: '0%',
      c: '0%',
      d: '0%',
      nr: '1%'
    }
  },
  {
    ticker: 'BSJP',
    url: '#',
    criteria: 'High Yield',
    maturityDate: 2025,
    yieldToMaturity: 5.42,
    yieldToWorst: 5.13,
    effectiveDuration: 3.09,
    monthSecYield: 5.55,
    distributionRate: 5.7,
    numberOfHoldings: 244,
    creditQuality: {
      aaa: '0%',
      aa: '0%',
      a: '0%',
      bbb: '0%',
      bb: '48%',
      b: '41%',
      ccc: '10%',
      cc: '0%',
      c: '0%',
      d: '0%',
      nr: '1%'
    }
  },
  {
    ticker: 'BSJQ',
    url: '#',
    criteria: 'High Yield',
    maturityDate: 2026,
    yieldToMaturity: 5.31,
    yieldToWorst: 5.04,
    effectiveDuration: 3.5,
    monthSecYield: 5.52,
    distributionRate: 5.76,
    numberOfHoldings: 167,
    creditQuality: {
      aaa: '0%',
      aa: '0%',
      a: '0%',
      bbb: '0%',
      bb: '56%',
      b: '37%',
      ccc: '6%',
      cc: '0%',
      c: '0%',
      d: '0%',
      nr: '1%'
    }
  },
  {
    ticker: 'BSAE',
    url: '#',
    criteria: 'Emerging Markets Debt',
    maturityDate: 2021,
    yieldToMaturity: 3.27,
    yieldToWorst: 3.27,
    effectiveDuration: 1.84,
    monthSecYield: 3.14,
    distributionRate: 'N/A',
    numberOfHoldings: 50,
    creditQuality: {
      aaa: '4%',
      aa: '4%',
      a: '19%',
      bbb: '29%',
      bb: '13%',
      b: '0%',
      ccc: '4%',
      cc: '0%',
      c: '0%',
      d: '0%',
      nr: '27%'
    }
  },
  {
    ticker: 'BSBE',
    url: '#',
    criteria: 'Emerging Markets Debt',
    maturityDate: 2022,
    yieldToMaturity: 3.49,
    yieldToWorst: 3.48,
    effectiveDuration: 2.66,
    monthSecYield: 3.37,
    distributionRate: 'N/A',
    numberOfHoldings: 54,
    creditQuality: {
      aaa: '5%',
      aa: '6%',
      a: '17%',
      bbb: '27%',
      bb: '8%',
      b: '2%',
      ccc: '0%',
      cc: '0%',
      c: '0%',
      d: '0%',
      nr: '35%'
    }
  },
  {
    ticker: 'BSCE',
    url: '#',
    criteria: 'Emerging Markets Debt',
    maturityDate: 2023,
    yieldToMaturity: 3.71,
    yieldToWorst: 3.65,
    effectiveDuration: 3.41,
    monthSecYield: 3.56,
    distributionRate: 'N/A',
    numberOfHoldings: 48,
    creditQuality: {
      aaa: '0%',
      aa: '2%',
      a: '16%',
      bbb: '41%',
      bb: '14%',
      b: '4%',
      ccc: '3%',
      cc: '0%',
      c: '0%',
      d: '0%',
      nr: '20%'
    }
  },
  {
    ticker: 'BSDE',
    url: '#',
    criteria: 'Emerging Markets Debt',
    maturityDate: 2024,
    yieldToMaturity: 4.08,
    yieldToWorst: 3.92,
    effectiveDuration: 4.01,
    monthSecYield: 4.15,
    distributionRate: 'N/A',
    numberOfHoldings: 48,
    creditQuality: {
      aaa: '0%',
      aa: '2%',
      a: '11%',
      bbb: '43%',
      bb: '21%',
      b: '11%',
      ccc: '0%',
      cc: '0%',
      c: '0%',
      d: '0%',
      nr: '12%'
    }
  }
];

export default productData;
